### PR TITLE
Add pre-commit hooks

### LINKED ISSUE #24: Add pre-commit hooks
Inspiration can be taken from here: https://github.com/nanotech-empa/general-issues/issues/5

### PR DESCRIPTION
**Pull request by yakutovicha**
fixes #24

### CODE REVIEW

**Comment by edoardob90** [comment]
Shouldn't `pre-commit` be added as a "dev" dependency somewhere?

**Comment by yakutovicha** [comment]
> Shouldn't `pre-commit` be added as a "dev" dependency somewhere?

At the moment I would add it to `environment.yml`.

If we want to make it a `dev` dependency, we should convert this repo into a proper Python package.

**Comment by yakutovicha** [comment]
Admittedly, I didn't fix all the issues reported by pre-commit. But slowly we will get there 👍

**Review by edoardob90 — CHANGES_REQUESTED** [review]
There might be a few other warnings to add to the ignore list, but I guess this is a good starting point 👍🏻

**Pull request merged**
