### PR TITLE
Added type hints.

### LINKED ISSUE #102: Add type hints in basic data types exercises

### PR DESCRIPTION
**Pull request by baffelli**
Closes #102

### CODE REVIEW

**Comment by despadam** [comment]
Shall we also add type hints to the reference solutions?

**Comment by yakutovicha** [comment]
> Shall we also add type hints to the reference solutions?

good catch, @despadam. I was about to approve it. @baffelli could you do that?

**Comment by baffelli** [comment]
> > Shall we also add type hints to the reference solutions?
> 
> good catch, @despadam. I was about to approve it. @baffelli could you do that?

Done in 5551d78

**Review by yakutovicha — DISMISSED** [review]
Quickly tested, seems to work fine.

I will go through a more careful check before the tutorial, in case of issues, I will update the material accordingly.

**Comment by baffelli** [comment]
> Quickly tested, seems to work fine.
> 
> I will go through a more careful check before the tutorial, in case of issues, I will update the material accordingly.

Can I merge then?

**Comment by yakutovicha** [comment]
> > Quickly tested, seems to work fine.
> > I will go through a more careful check before the tutorial, in case of issues, I will update the material accordingly.
> 
> Can I merge then?

There was a problem wit the pre-commit check. I just fixed it.

**Review by yakutovicha — APPROVED** [review]

**Pull request merged**
