### PR TITLE
Fixed tests.

### PR DESCRIPTION
**Pull request by baffelli**
Closing #134.

### CODE REVIEW

**Review by despadam — CHANGES_REQUESTED** [review]
The table of contents should be updated, for example it does not contain `exercise 3`.

Will also leave some additional comments for errors I came across when trying to execute the exercises.

**Comment by despadam** [comment]
When executing `solution_print_odd` I get `ValueError: I/O operation on closed file`

**Comment by despadam** [comment]
When executing `solution_print_salutation()` I get no output at all.

**Comment by despadam** [comment]
When executing `solution_write_file()` I get `Failed: Cannot read from inexistent file.`

**Comment by despadam** [comment]
When executing `solution_read_write_file()` I get `FileNotFoundError: [Errno 2] No such file or directory: '...\test_read_write_file_solution_0\\output_file.txt'`

**Comment by baffelli** [comment]
> When executing `solution_print_odd()` I get `ValueError: I/O operation on closed file`

Good catch, solved in [27fbfd8](https://github.com/empa-scientific-it/python-tutorial/pull/223/commits/27fbfd8442ea206b1429a2cbebb27859cdaebb18)

**Comment by baffelli** [comment]
> When executing `solution_print_salutation()` I get no output at all.

There's no test for that exercise because I could find no way to use `input` in iyptest

**Comment by baffelli** [comment]
> `solution_write_file`

I changed the error message in 506ac73

**Comment by baffelli** [comment]
> When executing `solution_read_write_file()` I get `FileNotFoundError: [Errno 2] No such file or directory: '...\test_read_write_file_solution_0\\output_file.txt'`

I was using `pytest.fail` instead of `assert`. This causes a confusing error message which is not properly handled by ipytest.
It is now fixed in f0e83ea

**Comment by baffelli** [comment]
> The table of contents should be updated, for example it does not contain `exercise 3`.
> 
> Will also leave some additional comments for errors I came across when trying to execute the exercises.

Done in [eaac18c](https://github.com/empa-scientific-it/python-tutorial/pull/223/commits/eaac18ca68c9e8a3e7519250f779645f2b429f12)

**Comment by despadam** [comment]
Hi @baffelli, all exercises run smoothly now, thanks! The only remaining topic is the TOC:
1. Due to incorrect indentation, the list appears as text instead of links.
2. Due to the bug we have not fixed, when you have multiple sections with the same title, the script will make all links with the same name point to the same section. Here you have multiple sections named `Exercises`, so whichever link you click, it will always send you to the first section with this name. A quick solution is to rename them and make each of the `Exercises` section have a slightly different title.

**Comment by baffelli** [comment]
> Hi @baffelli, all exercises run smoothly now, thanks! The only remaining topic is the TOC:
> 
>     1. Due to incorrect indentation, the list appears as text instead of links.
> 
>     2. Due to the bug we have not fixed, when you have multiple sections with the same title, the script will make all links with the same name point to the same section. Here you have multiple sections named `Exercises`, so whichever link you click, it will always send you to the first section with this name. A quick solution is to rename them and make each of the `Exercises` section have a slightly different title.

Thank you for the hint. I cannot reproduce these problems, for me the links work correctly.

**Comment by despadam** [comment]
> > Hi @baffelli, all exercises run smoothly now, thanks! The only remaining topic is the TOC:
> > ```
> > 1. Due to incorrect indentation, the list appears as text instead of links.
> > 
> > 2. Due to the bug we have not fixed, when you have multiple sections with the same title, the script will make all links with the same name point to the same section. Here you have multiple sections named `Exercises`, so whichever link you click, it will always send you to the first section with this name. A quick solution is to rename them and make each of the `Exercises` section have a slightly different title.
> > ```
> 
> Thank you for the hint. I cannot reproduce these problems, for me the links work correctly.


No worries. If it's ok then I am taking the liberty to rename the sections so the TOC will work correctly for all

**Review by despadam — APPROVED** [review]

**Review by baffelli — COMMENTED** [review]
Looks good to me

**Pull request merged**
